### ISSUE TITLE
[0.34.0] the trait bound `Vec<XYZ> : subxt::ext::parity_scale_codec::Decode` is not satisfied

### ISSUE THREAD

**Issue by shekohex** [paritytech/subxt#1603] opened 2024-05-21 17:55 UTC
I'm facing an issue with `Encode` and `Decode` not being implemented for the generated types. Consider the following complex type:

```rs
#[derive(Encode, Decode, TypeInfo, MaxEncodedLen)]
#[scale_info(bounds(AccountId: TypeInfo), skip_type_params(C))]
#[codec(encode_bound(skip_type_params(C)))]
#[codec(decode_bound(skip_type_params(C)))]
#[codec(mel_bound(skip_type_params(C)))]
#[cfg_attr(
	feature = "std",
	derive(Serialize, Deserialize),
	serde(bound(serialize = "AccountId: Serialize", deserialize = "AccountId: Deserialize<'de>"))
)]
pub enum Field<C: Constraints, AccountId> {
	/// Represents a field of null value.
	#[codec(index = 0)]
	None,
	/// Represents a boolean.
	#[codec(index = 1)]
	Bool(bool),
	/// Represents a u8 Number.
	#[codec(index = 2)]
	Uint8(u8),
	/// Represents a i8 Number.
	#[codec(index = 3)]
	Int8(i8),
	/// Represents a u16 Number.
	#[codec(index = 4)]
	Uint16(u16),
	/// Represents a i16 Number.
	#[codec(index = 5)]
	Int16(i16),
	/// Represents a u32 Number.
	#[codec(index = 6)]
	Uint32(u32),
	/// Represents a i32 Number.
	#[codec(index = 7)]
	Int32(i32),
	/// Represents a u64 Number.
	#[codec(index = 8)]
	Uint64(u64),
	/// Represents a i64 Number.
	#[codec(index = 9)]
	Int64(i64),
	/// Represents a UTF-8 string.
	#[codec(index = 10)]
	String(BoundedString<C::MaxFieldsSize>),
	/// Represents a Raw Bytes.
	#[codec(index = 11)]
	Bytes(BoundedVec<u8, C::MaxFieldsSize>),
	/// Represents an array of values
	/// Fixed Length of values.
	#[codec(index = 12)]
	Array(BoundedVec<Self, C::MaxFieldsSize>),
	/// Represents a list of values
	#[codec(index = 13)]
	List(BoundedVec<Self, C::MaxFieldsSize>),

	// NOTE: Special types starts from 100
	/// A sepcial type for AccountId
	#[codec(index = 100)]
	AccountId(AccountId),
}

```
> Full code could be found [here](https://github.com/webb-tools/tangle/blob/46c716d34b3a482dc1dd470599ffcc4133fe05c9/primitives/src/jobs/v2/field.rs#L59)

When compiled and using the CLI:
```sh
subxt metadata -f bytes > ./metadata/tangle-testnet-runtime.scale
```
Then generate the code from the metadata file
```sh
subxt codegen --file metadata/tangle-testnet-runtime.scale --derive Clone --derive Eq --derive PartialEq | rustfmt --edition=2021 --emit=stdout > src/tangle_testnet_runtime.rs
```

The generated code doesn't look lacking the traits
```rs
#[derive(
    :: subxt :: ext :: codec :: Decode,
    :: subxt :: ext :: codec :: Encode,
    :: subxt :: ext :: scale_decode :: DecodeAsType,
    :: subxt :: ext :: scale_encode :: EncodeAsType,
    Clone,
    Debug,
    Eq,
    PartialEq,
)]
# [codec (crate = :: subxt :: ext :: codec)]
#[decode_as_type(crate_path = ":: subxt :: ext :: scale_decode")]
#[encode_as_type(crate_path = ":: subxt :: ext :: scale_encode")]
pub enum Field<_1> {
    #[codec(index = 0)]
    None,
    #[codec(index = 1)]
    Bool(::core::primitive::bool),
    #[codec(index = 2)]
    Uint8(::core::primitive::u8),
    #[codec(index = 3)]
    Int8(::core::primitive::i8),
    #[codec(index = 4)]
    Uint16(::core::primitive::u16),
    #[codec(index = 5)]
    Int16(::core::primitive::i16),
    #[codec(index = 6)]
    Uint32(::core::primitive::u32),
    #[codec(index = 7)]
    Int32(::core::primitive::i32),
    #[codec(index = 8)]
    Uint64(::core::primitive::u64),
    #[codec(index = 9)]
    Int64(::core::primitive::i64),
    #[codec(index = 10)]
    String(runtime_types::tangle_primitives::jobs::v2::field::BoundedString),
    #[codec(index = 11)]
    Bytes(runtime_types::bounded_collections::bounded_vec::BoundedVec<::core::primitive::u8>),
    #[codec(index = 12)]
    Array(
        runtime_types::bounded_collections::bounded_vec::BoundedVec<
            runtime_types::tangle_primitives::jobs::v2::field::Field<_1>,
        >,
    ),
    #[codec(index = 13)]
    List(
        runtime_types::bounded_collections::bounded_vec::BoundedVec<
            runtime_types::tangle_primitives::jobs::v2::field::Field<_1>,
        >,
    ),
    #[codec(index = 100)]
    AccountId(_1),
}

```

But when building the crate, it does generate the following errors:
```
the trait `subxt::ext::parity_scale_codec::Encode` is not implemented for `[field::Field<AccountId32>]`, which is required by `Vec<field::Field<AccountId32>>: subxt::ext::parity_scale_codec::Encode`
```
```
the trait `subxt::ext::parity_scale_codec::Decode` is not implemented for `Vec<field::Field<AccountId32>>`
```

### Other Metadata
1. Using subxt 0.34.0
2. Using subxt-cli 0.34.0
3. Cargo.toml
```toml
[package]
name = "tangle-subxt"
version = "0.1.3-v2+001"
edition = 2021

[dependencies]
subxt = { version = "0.34.0", default-features = false, features = ["native", "jsonrpsee"] }
```
4. The metadata file could be found here: https://github.com/webb-tools/tangle/blob/46c716d34b3a482dc1dd470599ffcc4133fe05c9/tangle-subxt/metadata/tangle-testnet-runtime.scale

**Comment by jsdw** [comment] 2024-05-24 11:53
This is a weird one!

I don't have a resolution yet, but after some experimentation I found that you can replace:

```rust
#[codec(index = 12)]
Array(
    runtime_types::bounded_collections::bounded_vec::BoundedVec5<
        runtime_types::tangle_primitives::jobs::v2::field::Field<_1>,
    >,
),
#[codec(index = 13)]
List(
    runtime_types::bounded_collections::bounded_vec::BoundedVec5<
        runtime_types::tangle_primitives::jobs::v2::field::Field<_1>,
    >,
),
```

with

```rust
#[codec(index = 12)]
Array(
    runtime_types::bounded_collections::bounded_vec::BoundedVec5<
        Field<_1>,
    >,
),
#[codec(index = 13)]
List(
    runtime_types::bounded_collections::bounded_vec::BoundedVec5<
        Field<_1>,
    >,
),
```

and suddenly things start compiling OK again for me. I've no idea why though! Does that work for you too?

**Comment by jsdw** [comment] 2024-05-24 14:39
Just to add; if you replace subxt/examples/events.rs with this file:

https://gist.github.com/jsdw/b0d188f88197ef08100f3b51fffff7c8

And then run `cargo run --example events`, it'll reproduce the error. Search for `// jsdw` and remove the paths and the compile errors go away.

@niklasad1 / @pkhry any ideas? :)

**Comment by pkhry** [comment] 2024-05-27 07:13
Maybe reference to `Self` is getting resolved incorrectly during the codegen stage?

Does the error occur if `Self` is replaced with explicit `Field` in the definition site?

**Comment by shekohex** [comment] 2024-05-29 15:35
> Maybe reference to `Self` is getting resolved incorrectly during the codegen stage?
> 
> Does the error occur if `Self` is replaced with explicit `Field` in the definition site?

It did not work. @pkhry @jsdw

**Comment by jsdw** [comment] 2024-05-29 16:04
Did you try something like in my gist linked above and see that things started compiling again? or maybe it was just something werid on my end :)

**Comment by shekohex** [comment] 2024-05-29 20:37
> Did you try something like in my gist linked above and see that things started compiling again? or maybe it was just something werid on my end :)

I can confirm that your change fixes the issue. It makes the whole crate compiles. So it is an issue with the codegen then?

**Comment by jsdw** [comment] 2024-05-30 09:00
> I can confirm that your change fixes the issue. It makes the whole crate compiles. So it is an issue with the codegen then?

I'm not sure yet, because I don't know why adding the full paths to the types would cause any sort of issue! This needs more investigating to find a minimal reproducible example and try to narrow down what would be causing it.

**Comment by pkhry** [comment] 2024-05-31 10:49
Here i managed to do a minimal repro: 
```rust
#![allow(missing_docs)]

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    Ok(())
}

#[derive(
    :: subxt :: ext :: subxt_core :: ext :: codec :: Decode,
    :: subxt :: ext :: subxt_core :: ext :: codec :: Encode,
    :: subxt :: ext :: subxt_core :: ext :: scale_decode :: DecodeAsType,
    :: subxt :: ext :: subxt_core :: ext :: scale_encode :: EncodeAsType,
    Debug,
)]
# [codec (crate = :: subxt :: ext :: subxt_core :: ext :: codec)]
#[decode_as_type(crate_path = ":: subxt :: ext :: subxt_core :: ext :: scale_decode")]
#[encode_as_type(crate_path = ":: subxt :: ext :: subxt_core :: ext :: scale_encode")]
#[doc = "An new operator has been registered."]
pub struct Registered {
    pub registration_args: runtime::Field<u32>,
}

pub mod runtime {
    #[derive(
        :: subxt :: ext :: subxt_core :: ext :: codec :: Decode,
        :: subxt :: ext :: subxt_core :: ext :: codec :: Encode,
        :: subxt :: ext :: subxt_core :: ext :: scale_decode :: DecodeAsType,
        :: subxt :: ext :: subxt_core :: ext :: scale_encode :: EncodeAsType,
        Debug,
    )]
    #[codec (crate = :: subxt :: ext :: subxt_core :: ext :: codec)]
    #[decode_as_type(crate_path = ":: subxt :: ext :: subxt_core :: ext :: scale_decode")]
    #[encode_as_type(crate_path = ":: subxt :: ext :: subxt_core :: ext :: scale_encode")]
    pub enum Field<_1> {
        #[codec(index = 2)]
        Array(
            // jsdw: turn this to Field to resolve errors
            Box<super::runtime::Field<_1>>,
        ),
        #[codec(index = 1)]
        Data(_1),
    }
}

```
Still have no idea why trait inference fails when `Field<_>` refers to itself through `super::_`

**Comment by pkhry** [comment] 2024-06-03 09:02
cc @shekohex, 
After investigating more, we've got an answer from scale-codec maintainers: 
To fix issue of incorrect trait bounds in this specific case for enum `Field<_>` add `#[codec (dumb_trait_bound)]` to the definition.

**Comment by shekohex** [comment] 2024-06-03 15:45
> cc @shekohex, After investigating more, we've got an answer from scale-codec maintainers: To fix issue of incorrect trait bounds in this specific case for enum `Field<_>` add `#[codec (dumb_trait_bound)]` to the definition.

I did try that, but I did not work. Here is the updated code:
```
#[derive(Encode, Decode, TypeInfo, MaxEncodedLen)]
#[scale_info(bounds(AccountId: TypeInfo), skip_type_params(C))]
#[codec(encode_bound(skip_type_params(C)))]
#[codec(decode_bound(skip_type_params(C)))]
#[codec(mel_bound(skip_type_params(C)))]
#[codec(dumb_trait_bound)]
#[cfg_attr(
	feature = "std",
	derive(Serialize, Deserialize),
	serde(bound(serialize = "AccountId: Serialize", deserialize = "AccountId: Deserialize<'de>"))
)]
pub enum Field<C: Constraints, AccountId> {
	/// Represents a field of null value.
	#[codec(index = 0)]
	None,
	/// Represents a boolean.
	#[codec(index = 1)]
	Bool(bool),
	/// Represents a u8 Number.
	#[codec(index = 2)]
	Uint8(u8),
	/// Represents a i8 Number.
	#[codec(index = 3)]
	Int8(i8),
	/// Represents a u16 Number.
	#[codec(index = 4)]
	Uint16(u16),
	/// Represents a i16 Number.
	#[codec(index = 5)]
	Int16(i16),
	/// Represents a u32 Number.
	#[codec(index = 6)]
	Uint32(u32),
	/// Represents a i32 Number.
	#[codec(index = 7)]
	Int32(i32),
	/// Represents a u64 Number.
	#[codec(index = 8)]
	Uint64(u64),
	/// Represents a i64 Number.
	#[codec(index = 9)]
	Int64(i64),
	/// Represents a UTF-8 string.
	#[codec(index = 10)]
	String(BoundedString<C::MaxFieldsSize>),
	/// Represents a Raw Bytes.
	#[codec(index = 11)]
	Bytes(BoundedVec<u8, C::MaxFieldsSize>),
	/// Represents an array of values
	/// Fixed Length of values.
	#[codec(index = 12)]
	Array(BoundedVec<Field<C, AccountId>, C::MaxFieldsSize>),
	/// Represents a list of values
	#[codec(index = 13)]
	List(BoundedVec<Field<C, AccountId>, C::MaxFieldsSize>),

	// NOTE: Special types starts from 100
	/// A sepcial type for AccountId
	#[codec(index = 100)]
	AccountId(AccountId),
}

```
I've added `#[codec(dumb_trait_bound)]` on top of `enum Field<C: Constraints, AccountId>` but this did not change anything, actually.

**Comment by jsdw** [comment] 2024-06-03 16:03
> To fix issue of incorrect trait bounds in this specific case for enum Field<_> add #[codec (dumb_trait_bound)] to the definition.

 @shekohex yeah; this is something you'd want to add to the generated output rather than the "input" type you posted above. We will experiment with adding it by default to our codegen to see if it breaks anything or not; if this works, it should resolve this issue more properly!

**Comment by shekohex** [comment] 2024-06-03 16:20
> > To fix issue of incorrect trait bounds in this specific case for enum Field<_> add #[codec (dumb_trait_bound)] to the definition.
> 
> @shekohex yeah; this is something you'd want to add to the generated output rather than the "input" type you posted above. We will experiment with adding it by default to our codegen to see if it breaks anything or not; if this works, it should resolve this issue more properly!

This works, I guess that should be added by default to the generated code.

**Closed** 2024-06-05 15:45 UTC
