### ISSUE TITLE
LightClient storage iterator returns duplicates

### ISSUE THREAD

**Issue by ggwpez** [paritytech/subxt#1453] opened 2024-02-26 16:54 UTC
I am using the light client feature to try and iterate over all members of the Fellowship.  
Code looks like this:  
```rust
let key = collectives::storage().fellowship_collective().members_iter();
let mut query = parachain_api.storage().at_latest().await.unwrap().iter(key).await?;

while let Some(Ok((id, fellow))) = query.next().await {
    // ..
}
```

But somehow it returns duplicate values. The full code is on this branch: https://github.com/paritytech/subxt/compare/master...oty-light-client-iter-duplicate  
Note that it does work when using an RPC node.

**Comment by niklasad1** [comment] 2024-02-26 17:36
Thanks for the issue, we'll have a look at it soon.

@lexnv I guess you may have some hunch about this one :)

**Comment by lexnv** [comment] 2024-02-26 17:42
I was able to reproduce this locally. My first hunch is that smoldot is providing us duplicate answers.

The duplication is checked by account ID at the provided branch, which is a subset of the provided ID. However, I was also able to reproduce this with the ID unaltered.

**Comment by lexnv** [comment] 2024-02-26 18:01
We have two different backends.

The legacy backend, which makes calls to the legacy RPC methods (ie `chain_subscribeFinalizedHeads`).
And an unstable backend, which makes calls to the RPC V2 methods (ie `chainHead_unstable_follow`). For more info, check https://github.com/paritytech/json-rpc-interface-spec. The backend is called unstable to reflect that `chainHead` and `transaction` APIs are in flux.

When we construct a light-client instance in subxt, the default backend is the legacy one.
However, the RPC V2 was introduced to make the integration with light-clients better. 

I've encountered a similar issue with the legacy RPCs in combination with smoldot at: https://github.com/smol-dot/smoldot/issues/1638.

Next steps here:
- I'll raise an issue tomorrow in smoldot with some extra details
- I'll change the default backend for the smoldot to the unstable backend in a future PR (with option to fallback/use the legacy backend -- that will allow us to do extensive testing in the near future on the unstable-lightclient)

Meanwhile, I've got a patch to unblock you Oliver: https://github.com/paritytech/subxt/compare/lexnv/oty-light-client-iter-duplicate-unstable?expand=1 (uses the unstable backend for light-clients), let me know if this helps 🙏 

Thanks again for raising this!

**Comment by jsdw** [comment] 2024-02-27 09:48
> I'll change the default backend for the smoldot to the unstable backend in a future PR (with option to fallback/use the legacy backend -- that will allow us to do extensive testing in the near future on the unstable-lightclient)

Rather than doing that right now (remember, doing so would requite that users take the `UnstableBackendDriver` and run it in a task, which is fine but because it's not what "normal" subxt does yet, I'd rather wait till we have a "standard" approach for this), I think a great option would be to allow the `LightClientBuilder` to be built from an arbitrary `Backend` in the same way that the `OnlineClient` is; this would allow people (and us) to experiment with both backends more easily without committing to any particular higher level interface just yet :)

**Comment by jsdw** [comment] 2024-03-21 10:52
Just FYI, I merged a PR recently to revamp the light client interface which should help work around this: https://github.com/paritytech/subxt/blob/master/subxt/examples/light_client_basic.rs

The idea now is that you construct an `RpcClient` implementaiton which is the light client, and then pass that to Subxt to initialise it. In the example above, we just initialise an `OnlineClient` directly (which defaults to using the `LegacyBackend`, ie the old RPC methods, under the hood), but now you can also instantiate a backend to use the new (but still unstable!) RPCs with something like so:

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // The lightclient logs are informative:
    tracing_subscriber::fmt::init();

    // Instantiate a light client with the Polkadot relay chain,
    // and connect it to Asset Hub, too.
    let (lightclient, polkadot_rpc) = LightClient::relay_chain(POLKADOT_SPEC)?;
    let asset_hub_rpc = lightclient.parachain(ASSET_HUB_SPEC)?;

    let (unstable_backend, driver) = subxt::backend::UnstableBackend::builder().build(asset_hub_rpc);

    // Unstable backend needs manually driving at the moment (this way, people
    // can choose which async runtime to use):
    tokio::spawn!(async move {
        while let Some(val) = driver.next().await {
            if let Err(e) = val {
                // Something went wrong driving unstable backend.
                break;
            }
        }
    })

    // Create Subxt clients from this unstable backend (ie using new RPCs).
    let polkadot_api = OnlineClient::<PolkadotConfig>::from_backend(unstable_backend).await?;
}
```

**Closed** 2024-04-15 10:42 UTC
Labels: bug

**Comment by jsdw** [comment] 2024-04-15 10:43
The issue here was the Smoldot state_getKeysPaged API being different from the Substrate one (ie returning the `start_key` provided). I pushed a small workaround in Subxt in #1534 which will remove such a key if it exists, but hopefully the issue will be fixed upstream via the above Smoldot issue.

**Comment by jsdw** [comment] 2024-09-03 15:32
I added some logging to the fetching logic in the reproducible example above and got this:

```text
Getting keys via state_get_keys_paged, pagination key:
None

Response:
[..., 223, 205, 161, 94, 52, 125, 117, 129, 32, 0, 0, 0]
[..., 44, 25, 84, 221, 159, 83, 207, 140, 38, 0, 0, 0]
[..., 26, 135, 220, 230, 199, 76, 76, 75, 37, 0, 0, 0]
[..., 64, 27, 83, 75, 157, 178, 6, 157, 52, 0, 0, 0]
[..., 80, 86, 200, 52, 234, 218, 252, 96, 39, 0, 0, 0]
[..., 176, 167, 35, 181, 81, 88, 134, 247, 58, 0, 0, 0]
[..., 9, 140, 98, 168, 3, 250, 164, 204, 48, 0, 0, 0]
[..., 4, 197, 200, 180, 230, 223, 147, 109, 40, 0, 0, 0]
[..., 3, 129, 165, 252, 69, 122, 161, 92, 54, 0, 0, 0]
[..., 1, 207, 232, 191, 118, 186, 39, 240, 30, 0, 0, 0]
[..., 62, 31, 98, 149, 228, 158, 210, 73, 44, 0, 0, 0]
[..., 60, 201, 195, 83, 192, 115, 126, 211, 41, 0, 0, 0]
[..., 56, 163, 88, 145, 190, 247, 174, 97, 57, 0, 0, 0]
[..., 79, 255, 102, 183, 202, 99, 22, 40, 33, 0, 0, 0]
[..., 87, 204, 157, 39, 224, 160, 78, 248, 45, 0, 0, 0]
[..., 84, 152, 146, 212, 75, 173, 214, 175, 19, 0, 0, 0]
[..., 107, 237, 251, 209, 118, 23, 153, 53, 43, 0, 0, 0]
[..., 106, 90, 114, 245, 120, 124, 177, 160, 53, 0, 0, 0]
[..., 127, 175, 90, 238, 118, 182, 218, 148, 47, 0, 0, 0]
[..., 114, 78, 207, 196, 142, 235, 76, 76, 31, 0, 0, 0]
[..., 142, 35, 63, 151, 34, 211, 14, 191, 49, 0, 0, 0]
[..., 135, 53, 27, 25, 242, 38, 254, 170, 24, 0, 0, 0]
[..., 146, 111, 238, 114, 211, 113, 249, 11, 51, 0, 0, 0]
[..., 146, 111, 57, 101, 250, 244, 95, 15, 22, 0, 0, 0]
[..., 169, 236, 99, 206, 125, 54, 124, 87, 27, 0, 0, 0]
[..., 166, 178, 116, 37, 14, 103, 83, 240, 10, 0, 0, 0]
[..., 190, 147, 216, 164, 206, 119, 153, 192, 11, 0, 0, 0]
[..., 202, 240, 66, 122, 170, 21, 230, 225, 56, 0, 0, 0]
[..., 194, 217, 103, 92, 249, 93, 207, 26, 17, 0, 0, 0]
[..., 243, 99, 65, 191, 187, 10, 78, 146, 50, 0, 0, 0]
[..., 241, 252, 80, 125, 59, 251, 253, 63, 36, 0, 0, 0]
[..., 241, 11, 197, 47, 182, 215, 86, 215, 42, 0, 0, 0]
[..., 71, 231, 30, 139, 171, 141, 241, 107, 55, 0, 0, 0]
[..., 71, 211, 225, 20, 88, 189, 183, 210, 59, 0, 0, 0]

Getting keys via state_get_keys_paged, pagination key:
Some([..., 71, 211, 225, 20, 88, 189, 183, 210, 59, 0, 0, 0])

Response:
[..., 223, 205, 161, 94, 52, 125, 117, 129, 32, 0, 0, 0]
[..., 80, 86, 200, 52, 234, 218, 252, 96, 39, 0, 0, 0]
[..., 176, 167, 35, 181, 81, 88, 134, 247, 58, 0, 0, 0]
[..., 79, 255, 102, 183, 202, 99, 22, 40, 33, 0, 0, 0]
[..., 87, 204, 157, 39, 224, 160, 78, 248, 45, 0, 0, 0]
[..., 84, 152, 146, 212, 75, 173, 214, 175, 19, 0, 0, 0]
[..., 107, 237, 251, 209, 118, 23, 153, 53, 43, 0, 0, 0]
[..., 106, 90, 114, 245, 120, 124, 177, 160, 53, 0, 0, 0]
[..., 127, 175, 90, 238, 118, 182, 218, 148, 47, 0, 0, 0]
[..., 114, 78, 207, 196, 142, 235, 76, 76, 31, 0, 0, 0]
[..., 142, 35, 63, 151, 34, 211, 14, 191, 49, 0, 0, 0]
[..., 135, 53, 27, 25, 242, 38, 254, 170, 24, 0, 0, 0]
[..., 146, 111, 238, 114, 211, 113, 249, 11, 51, 0, 0, 0]
[..., 146, 111, 57, 101, 250, 244, 95, 15, 22, 0, 0, 0]
[..., 169, 236, 99, 206, 125, 54, 124, 87, 27, 0, 0, 0]
[..., 166, 178, 116, 37, 14, 103, 83, 240, 10, 0, 0, 0]
[..., 190, 147, 216, 164, 206, 119, 153, 192, 11, 0, 0, 0]
[..., 202, 240, 66, 122, 170, 21, 230, 225, 56, 0, 0, 0]
[..., 194, 217, 103, 92, 249, 93, 207, 26, 17, 0, 0, 0]
[..., 243, 99, 65, 191, 187, 10, 78, 146, 50, 0, 0, 0]
[..., 241, 252, 80, 125, 59, 251, 253, 63, 36, 0, 0, 0]
[..., 241, 11, 197, 47, 182, 215, 86, 215, 42, 0, 0, 0]
[..., 71, 231, 30, 139, 171, 141, 241, 107, 55, 0, 0, 0]
[..., 71, 211, 225, 20, 88, 189, 183, 210, 59, 0, 0, 0]
```

I elided the start of the keys because they are all identical. Here, we see the API using the correct "pagination start key" to retrieve the second batch, but ultimately the response back from Smoldot 0.16 is overlapping in many entries.

Subxt tried to avoid this sort of issue by ignorign the _first_ key we get back if it's identical to the "pagination start key", but this fix is obviously not working out here.

The fix I think will have to be to use the currently unstable backend against Smoldot 0.18, as I can't see an obvious way to avoid this issue in Subxt offhand.
