### ISSUE TITLE
Regression in speed of fetching child storage values in 0.32

### ISSUE THREAD

**Issue by DamianStraszak** [paritytech/subxt#1195] opened 2023-10-06 19:34 UTC
As I understand, when iterating over a map in the storage, this constant
`const STORAGE_FETCH_PAGE_SIZE: u32 = 32;`
is used to determine how many keys should be fetched at once. 

This being a constant is quite limiting -- in fact for maps of size a few thousands, this becomes slow because of this constant being too small. Ideally it should be possible to pass this into `iter()` or somewhere, so that one can configure the page size depending on factors like size of the key and value, instead of using a constant.

**Comment by jsdw** [comment] 2023-10-06 22:57
The reason that this isn't configurable in the api now is that the new RPC methods stream storage entries, and the subxt interface needs to play nicely with both (until the new RPCs stabilise).

I think the solution here is probably something like to make it configurable in the LegacyBackend (ie the backend that uses the old RPC methods), possibly "on the fly" so that it can be set before a specific call where needed. It's less simple than before, but keeps the "unique to old RPCs" behaviour out of the main subxt interface.

**Comment by DamianStraszak** [comment] 2023-10-07 19:23
Thank you! 

I wasn't aware the new json-rpc is already implemented. But if I understand correctly, still the `LegacyBackend` is used by default?

So I guess, the simplest solution for me would be to fork subxt and just change the constant, correct?

**Comment by DamianStraszak** [comment] 2023-10-07 20:18
Let me just give some context. I'm trying to diagnose why my code is running so slow with `subxt` :/

I have the following code that fetches the `ContractInfoOf` map from Aleph Zero mainnet.
```
use std::collections::BTreeMap;
use azero::runtime_types::pallet_contracts::storage::ContractInfo;
use subxt::{OnlineClient, PolkadotConfig};
use subxt::utils::AccountId32;


type Client = OnlineClient::<PolkadotConfig>;

#[subxt::subxt(runtime_metadata_path = "./metadata/azero-mainnet.scale")]
pub mod azero {}

fn contract_info_of_key_to_account_id(key: &Vec<u8>) -> AccountId32 {
    let account_bytes = key[40..].to_vec();
    let array_u8: [u8; 32] = account_bytes.as_slice().try_into().unwrap();
    let account = AccountId32::from(array_u8);
    account
}

async fn get_contracts(api: &Client) -> BTreeMap<AccountId32, ContractInfo> {
    let storage_query = azero::storage().contracts().contract_info_of_iter();
    let mut res = BTreeMap::new();
    let mut stream = api.storage().at_latest().await.unwrap().iter(storage_query).await.unwrap();
    let mut now = std::time::Instant::now();
    while let Some(Ok((key, value))) = stream.next().await {
        let account = contract_info_of_key_to_account_id(&key);
        res.insert(account, value);
        let current = std::time::Instant::now();
        println!("{} ms", current.duration_since(now).as_millis());
        now = current;
    }
    res
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let api = OnlineClient::<PolkadotConfig>::from_url("wss://ws.azero.dev").await?;
    let cnt = get_contracts(&api).await.len();
    println!("Total {} contracts", cnt);
    Ok(())
}
```

The metadata here is generated using `subxt metadata --url wss://ws.azero.dev -f bytes > metadata/azero-mainnet.scale`

Now, even when running in `release` mode, this takes ~25 sec to execute. And -- what is very weird, each stream item takes >= ~50ms to fetch. I would expect that since there is paging by 32, then it would be like: 32 0's, then non-zero time, 32 0's, then non-zero. Etc.

For comparison, when fetching the same map using the python library  (https://github.com/polkascan/py-substrate-interface) simply `query_map(module='Contracts',storage_function='ContractInfoOf')`, it takes ~2sec. The python library does the same as the LegacyBackend, but with paging of 100. So I have no idea where the difference is coming from...

**Comment by jsdw** [comment] 2023-10-07 21:52
Aah, I think that we also moved to fetching keys in batches and then items one by one as part of this migration to using a Backend trait, because I wasn't confident that the RPC method we were using previously would always do the right thing. We should look into making that faster again as a step 1, and then if the page size still benefits enough from being configurable then we can look at that next as an option when configuring a LegacyBackend.

Options for you to fix this much quicker:
- Stick with 0.31 until it's resolved; this should be quicker and also allows page size configuration, so is probably the way to go for now.
- Try the new UnstableBackend (although with the caveat that it may change in a breaking way, and it was merged into substrate not super long ago so may not be available on Aleph Zero yet). This also isn't well documented yet.

I'll make this a priority to look into, but am at a work event at the moment and so may not be quite as quick as usual! Sorry that this caused an issue for you!

**Comment by DamianStraszak** [comment] 2023-10-08 08:22
Thank you @jsdw, it's not issue at all. At least I learned a few new things :).

0.31 works great for me -- twice so fast as the python lib now, 

I also tried the `UnstableBackend` but didn't manage to get it working (the Aleph Zero mainnet is on `polkadot-v0.9.38` so it has a few `chainHead_unstable_` methods, but maybe not all?, I also tried with `polkadot-v1.0.0` but it didn't work either, maybe still too old). 

Is below the correct way to use `UnstableBackend`?

```
let rpc_client = rpc::RpcClient::from_url("wss://ws.azero.dev:443")
        .await
        .map_err(|e| format!("Cannot construct RPC client: {e}"))?;

    let (backend, mut driver) = unstable::UnstableBackend::builder().build(rpc_client);

    // The unstable backend needs driving:
    tokio::spawn(async move {
        use futures::StreamExt;
        while let Some(val) = driver.next().await {
            if let Err(e) = val {
                eprintln!("Error driving unstable backend: {e}");
                break;
            }
        }
    });
    let api = OnlineClient::from_backend(Arc::new(backend))
        .await
        .map_err(|e| format!("Cannot construct OnlineClient from backend: {e}"))?;
   ```
   
   Anyway. My question is answered. Feel free to close to issue.

**Comment by jsdw** [comment] 2023-10-08 21:59
Yup that's the right way to try out the unstable backend at the moment! And yeah, ok, that makes sense; the required code has only recently merged to master so I'm not at all surprised if it doesn't work yet :)

Ill leave this issue open and use it to track a fix for the performance regression you spotted so that we can get 0.32 back up to the same speed as 0.31 if we're able! Thanks for letting us know :)

**Closed** 2023-10-11 12:33 UTC
