### ISSUE TITLE
Failed to send transaction to the latest substrate

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/subxt#378] opened 2021-12-28 04:16 UTC
Got the error below. Looks like the upstream introduced some breaking changes:

```
Rpc(Request("{"jsonrpc":"2.0","error":{"code":1002,"message":"Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: Some(Error { cause: None, desc: \"Could not decode Call, variant doesn't exist\" }), desc: \"Could not decode Call::System.0\" } })","data":"RuntimeApi(\"Execution failed: ApiError(FailedToConvertParameter { function: \\\"validate_transaction\\\", parameter: \\\"tx\\\", error: Error { cause: Some(Error { cause: None, desc: \\\"Could not decode Call, variant doesn't exist\\\" }), desc: \\\"Could not decode Call::System.0\\\" } })\")"}
```

**Comment by shekohex** [comment] 2021-12-30 17:41
I'm facing the same issue with https://github.com/paritytech/substrate/commit/f57c6447af83a1706041d462ca290b4f2a1bac4f

**Comment by ascjones** [comment] 2022-01-03 10:50
I'm back tomorrow will take a look then.

**Comment by ascjones** [comment] 2022-01-04 10:14
Can you provide a reproduction for this? I have just run the unit tests against the latest substrate https://github.com/paritytech/substrate/commit/cd3d2b1b65929bafa699953094bcd8b9fe7d3dfc.

Possibly you need to regenerate your metadata file and do a clean build?

**Comment by shekohex** [comment] 2022-01-04 15:10
Ok, I've made the minimal Example, @ascjones please follow these steps:

1. Clone the node locally
```
git clone --depth 1 -b shady.update-substrate https://github.com/webb-tools/dkg-substrate.git
```
2. Build the node into `release` mode (should take less than 10min).
```
cargo build --release -p dkg-standalone-node
```
3. Then, Run the script that will run (3 nodes, for bootstrapping)
```
./scripts/run-standalone.sh
```
4. once it is working, you can clone the SDK and run the test
```
git clone --depth 1 https://github.com/webb-tools/webb-rs.git
```
5. Running the `acknowledge_proposal_works` test
```
cargo test acknowledge_proposal_works
```

You will get that error, similar to this:
```
Error: Rpc error: JSON-RPC request error: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":1002,\"message\":\"Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: \\\"validate_transaction\\\", parameter: \\\"tx\\\", error: Error { cause: Some(Error { cause: None, desc: \\\"Could not decode `Call`, variant doesn't exist\\\" }), desc: \\\"Could not decode `Call::System.0`\\\" } })\",\"data\":\"RuntimeApi(\\\"Execution failed: ApiError(FailedToConvertParameter { function: \\\\\\\"validate_transaction\\\\\\\", parameter: \\\\\\\"tx\\\\\\\", error: Error { cause: Some(Error { cause: None, desc: \\\\\\\"Could not decode `Call`, variant doesn't exist\\\\\\\" }), desc: \\\\\\\"Could not decode `Call::System.0`\\\\\\\" } })\\\")\"},\"id\":5}"
```

**Comment by ascjones** [comment] 2022-01-07 11:16
Hi @shekohex, I was able to reproduce your error following your steps so thanks. 

I wasn't able to determine exactly what was going on, but updating `subxt` to the latest version:

```patch
diff --git a/Cargo.toml b/Cargo.toml
index eb08187..ca092e5 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -37,7 +37,7 @@ native-tls = { version = "^0.2", features = ["vendored"] }
 [dependencies.subxt]
 git = "https://github.com/paritytech/subxt.git"
 version = "0.15.0"
-rev = "7aac7dfec" # https://github.com/paritytech/subxt/commit/7aac7dfec
+rev = "ca5345c" # https://github.com/paritytech/subxt/commit/ca5345c
 optional = true
 
 [dev-dependencies]
@@ -56,7 +56,7 @@ frame-metadata = { version = "14.0.0", features = ["v14", "std"], optional = tru
 [build-dependencies.subxt-codegen]
 git = "https://github.com/paritytech/subxt.git"
 version = "0.2.0"
-rev = "7aac7dfec" # https://github.com/paritytech/subxt/commit/7aac7dfec
+rev = "ca5345c" # https://github.com/paritytech/subxt/commit/ca5345c
 optional = true
```
```patch
diff --git a/tests/dkg.rs b/tests/dkg.rs
index 79fb0d7..b3bf12a 100644
--- a/tests/dkg.rs
+++ b/tests/dkg.rs
@@ -1,8 +1,9 @@
+use subxt::{DefaultConfig, DefaultExtra};
 use webb::substrate::dkg_runtime::api::{
-    dkg_proposals, DefaultConfig, RuntimeApi,
+    dkg_proposals, RuntimeApi,
 };
 
-type DKGRuntimeApi = RuntimeApi<DefaultConfig>;
+type DKGRuntimeApi = RuntimeApi<DefaultConfig, DefaultExtra<DefaultConfig>>;
 
 const URL: &str = "ws://localhost:9944";
```

and regenerating your code did seem to resolve that particular error. Possibly to do with the signed extensions, I don't know for sure.

The verification does succeed in this case, but the test does hang for me, not sure why that is, please have a go and see if that works for you.

Out of interest why are you using the codegen crate directly from the build script rather than the macro?

**Comment by shekohex** [comment] 2022-01-07 13:22
Hello @ascjones Thank you very much, it now works for me and for the test hangs, I guess we did a few updates and it now works and I also can see this from Polkadot-UI 
![image](https://user-images.githubusercontent.com/14620076/148549618-ea25ccb6-4d60-4daf-be8e-9d3d6b2f996c.png)

> Out of interest why are you using the codegen crate directly from the build script rather than the macro?

Well for a few reasons:
1. all of our team members can take a look at the generated code without actually cloning the repo locally, just right from GitHub.
2. Easier for IDE and especially, rust-analyzer sometimes breaks when it works with a lot of big macros.
3. Faster compile-time, since the code is never generated again, it is being already generated from `build.rs`, and never runs when we use our SDK since it is behind a feature flag.

**Comment by ascjones** [comment] 2022-01-07 14:24
> Easier for IDE and especially, rust-analyzer sometimes breaks when it works with a lot of big macros.

Yeah this is a big one, would help massively with the discoverability of the API if code completion worked for the macro.

**Comment by ascjones** [comment] 2022-01-07 14:25
> Thank you very much, it now works for me and for the test hangs, I guess we did a few updates and it now works and I also can see this from Polkadot-UI

If it's resolved for you now please close this issue.

**Comment by ascjones** [comment] 2022-01-07 14:41
Actually just noticed it was @h4x3rotab who opened this: can you confirm that updating to the latest `master` fixes the issue?

**Comment by jsdw** [comment] 2022-01-14 15:55
I'm going to assume that this is resolved for now and close the issue, but please feel free to re-open if that is not the case!

**Closed by jsdw** 2022-01-14 15:55 UTC

**Comment by f-squirrel** [comment] 2023-07-02 18:47
> I'm facing the same issue with [paritytech/substrate@f57c644](https://github.com/paritytech/substrate/commit/f57c6447af83a1706041d462ca290b4f2a1bac4f)

Hey, I know that it is an old issue. I have noticed that since I have added `subxt` macro, the project is longer to build, and autocompletion takes ages. Is there a way to run the macro once and somehow add it to the project?

Thank you!

**Comment by jsdw** [comment] 2023-07-03 07:14
You can use the subxt CLI tool's `codegen` command to spit out the same code that the macro generates (I'd suggest piping the output through `rustfmt` too).

That said, in either the macro or codegen case it'll have to recompile each time you change something in the crate. One approach to avoid this would be to run the macro (or put the codegen) into a separate crate so that it's not recompiled each time you edit the main crate.
