### ISSUE TITLE
How to run the examples - getting Error: wabt (could not compile `wabt-sys` with file too small to be an archive)

### ISSUE THREAD

**Issue by byteflyfunny** [paritytech/subxt#323] opened 2021-11-16 11:42 UTC
I want to run an example fetch_remote.rs .But failed when compilling the wabt-sys .I get some message like this
"error: failed to add native library ~/Project/subxt/target/debug/build/wabt-sys-4c43336a36cf24e1/out/build/libwabt.a: file too small to be an archive"
I use macbook pro with m1 arm.
I use the branch = "master"  commit = 57ab87b5a56d39e5143bb9c790652183481d8cb4

**Comment by jsdw** [comment] 2021-12-01 16:30
I haven't had time to dig into this, but offhand it appears as if this is an issue with Rust, potentially related to how you've installed it. Have a look at https://github.com/rust-lang/rust/issues/50220

FWIW I have an M1 Mac as well and I haven't run into the same issue. I'll close this issue for now, but please re-open if you have reason to think that the issue is more specific to this project :)

**Closed by jsdw** 2021-12-01 16:30 UTC
