### ISSUE TITLE
What is wrong with my metatada.scale file?

### ISSUE THREAD

**Issue by amrbz** [paritytech/subxt#475] opened 2022-03-14 09:57 UTC
Hi,
After upgrading to version 0.18 I've experienced these issues with metadata.scale file. I'm a bit confused on how to fix this. Thanks!

<img width="1512" alt="Screenshot 2022-03-14 at 12 46 33" src="https://user-images.githubusercontent.com/13852826/158147801-39f22ade-2500-4206-bbe0-a8fb03dc8827.png">

**Comment by jsdw** [comment] 2022-03-14 10:42
Those errors are saying that the types in question don't implement `parity-scale-codec`'s `Decode` trait.

If the issue is in the code generated by subxt, you can use the CLI tool to spit out the generated code from the  `metadata.scale` file. Then, looking for those types, you may be able to see why they don't implement Decode properly.

In the subxt folder you can do this with:

```
cargo run -- codegen -f /path/to/metadata.scale | rustfmt > test_output.rs
```

If you can't get to the bottom of the issue following this approach, then we may be able to provide more assistance if you can give us some steps to reproduce the issue :)

**Comment by amrbz** [comment] 2022-03-14 11:21
Thanks for the quick reply. I've managed to fix the issue by upgrading the subtx-cli and recompiling the metadata.scale file. My bad )

**Comment by jsdw** [comment] 2022-03-14 11:26
Awesome, good to hear! I'll close this now then :)

**Closed by jsdw** 2022-03-14 11:26 UTC
