### ISSUE TITLE
ExtrinsicSuccess event decoding error

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#617] opened 2022-08-12 09:01 UTC
With the latest release `0.23.0` I get the following error decoding `ExtrinsicSuccess` (when testing https://github.com/paritytech/cargo-contract/pull/678)

![image](https://user-images.githubusercontent.com/75586/184321439-1bc30391-0986-44db-b9f5-bf0e659bbb2d.png)

Here are the `DEBUG` logs:

```
 Event System ➜ ExtrinsicSuccess
[2022-08-12T08:59:49Z DEBUG contract_transcode::decode] Decoding input with type id `19` and definition `Type { path: Path { segments: ["frame_support", "weights", "DispatchInfo"] }, type_params: [], type_def: Composite(TypeDefComposite { fields: [Field { name: Some("weight"), ty: UntrackedSymbol { id: 8, marker: PhantomData }, type_name: Some("Weight"), docs: [] }, Field { name: Some("class"), ty: UntrackedSymbol { id: 20, marker: PhantomData }, type_name: Some("DispatchClass"), docs: [] }, Field { name: Some("pays_fee"), ty: UntrackedSymbol { id: 21, marker: PhantomData }, type_name: Some("Pays"), docs: [] }] }), docs: [] }`
[2022-08-12T08:59:49Z DEBUG contract_transcode::env_types] No custom decoder found for type 19
[2022-08-12T08:59:49Z DEBUG contract_transcode::decode] Decoding input with type id `8` and definition `Type { path: Path { segments: [] }, type_params: [], type_def: Primitive(U64), docs: [] }`
[2022-08-12T08:59:49Z DEBUG contract_transcode::env_types] No custom decoder found for type 8
[2022-08-12T08:59:49Z DEBUG contract_transcode::decode] Decoding input with type id `20` and definition `Type { path: Path { segments: ["frame_support", "weights", "DispatchClass"] }, type_params: [], type_def: Variant(TypeDefVariant { variants: [Variant { name: "Normal", fields: [], index: 0, docs: [] }, Variant { name: "Operational", fields: [], index: 1, docs: [] }, Variant { name: "Mandatory", fields: [], index: 2, docs: [] }] }), docs: [] }`
[2022-08-12T08:59:49Z DEBUG contract_transcode::env_types] No custom decoder found for type 20
ERROR: Error decoding type 19: frame_support::weights::DispatchInfo

Caused by:
    0: Error decoding type 20: frame_support::weights::DispatchClass
    1: No variant found with discriminant 52
```

This appears to be a regression in https://github.com/paritytech/subxt/pull/607, since I have tried with the previous commit and the same error does not occur.

**Comment by jsdw** [comment] 2022-08-12 09:34
Ooh I'll have a look! What would be the best steps to reproduce this bug?

**Comment by ascjones** [comment] 2022-08-12 09:54
3 terminal windows:

1. checkout `cargo-contract` with this branch https://github.com/paritytech/cargo-contract/pull/678
2. clone https://github.com/paritytech/ink/ && cd ink/examples/flipper
3. clone `https://github.com/paritytech/substrate-contracts-node/` and `cargo run -- --dev --tmp`. Or just download the binary: https://github.com/paritytech/substrate-contracts-node/#download-binary and run it.

In terminal `2.`, build the contract with: 

```
cargo run --release --manifest-path=../cargo-contract/Cargo.toml -- \
       contract build --skip-linting
``` 
Then instantiate it:

```
cargo run --release --manifest-path=/home/andrew/code/cargo-contract/Cargo.toml -- \
       contract instantiate \
      --args false \
      --suri //Alice \
      --salt 0x07
```

You can increment the `--salt` flag for subsequent runs.

Alternatively to all that, you could just modify an existing integration test/example to parse all the events to see whether it fails with a similar error?

**Comment by jsdw** [comment] 2022-08-12 10:43
The root cause of this was not a bug in subxt, but more a naming change that wasn't very carefully thought through!

When you get hold of events and then iterate over each event:
- previously calling `event.bytes()` would return _only the bytes for the fields of the event_`. 
- Now, `event.bytes()` returns _all_ of the bytes associated with an event (it seemed like the more logical/expected approach), and there's a new call, `event.field_bytes()` that you can use to return the bytes for just the field data in the event (and these are the bytes you normally care about for decoding into static types for instance).

Anyway, with that in mind, I'll close this bug. Sorry for the confusion! In hindsight both names should have been changed to trigger a compile error so that you had to decide which method was most appropriate.

**Closed by jsdw** 2022-08-12 10:43 UTC
Labels: bug
